package com.example.colonpath_ai.screens.newcase

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.colonpath_ai.model.Case
import com.example.colonpath_ai.model.CaseStatus
import com.example.colonpath_ai.model.PatientInfo
import androidx.compose.material3.MaterialTheme
import com.example.colonpath_ai.ui.theme.BackgroundLight
import com.example.colonpath_ai.ui.theme.RedError
import com.example.colonpath_ai.ui.theme.SurfaceWhite
import com.example.colonpath_ai.ui.theme.TextPrimary
import com.example.colonpath_ai.ui.theme.TextSecondary

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun NewCaseScreen(
    onBack: () -> Unit,
    onProceed: (Case) -> Unit
) {
    val autoGeneratedCaseId = remember { com.example.colonpath_ai.data.SampleDataRepository.generateNextCaseId() }

    var patientId by remember { mutableStateOf("") }
    var patientName by remember { mutableStateOf("") }
    var caseId by remember { mutableStateOf(autoGeneratedCaseId) }
    var tissue by remember { mutableStateOf("") }
    var sampleType by remember { mutableStateOf("") }
    var stain by remember { mutableStateOf("") }
    var analysisDate by remember { mutableStateOf("") }
    var notes by remember { mutableStateOf("") }

    val isCaseIdDuplicate = remember(caseId, com.example.colonpath_ai.data.SampleDataRepository.sampleCaseHistory.toList()) {
        com.example.colonpath_ai.data.SampleDataRepository.isCaseIdExists(caseId.trim())
    }

    val isFormValid = patientName.isNotBlank() && caseId.isNotBlank() && !isCaseIdDuplicate

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("New Case") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = SurfaceWhite,
                    titleContentColor = TextPrimary,
                    navigationIconContentColor = TextPrimary
                )
            )
        }
    ) { paddingValues ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .background(BackgroundLight)
                .padding(paddingValues)
                .padding(horizontal = 20.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            item {
                Spacer(modifier = Modifier.height(8.dp))
                TextButton(
                    onClick = {
                        patientId = "PT-2026-0847"
                        patientName = "Sample Patient"
                        caseId = com.example.colonpath_ai.data.SampleDataRepository.generateNextCaseId()
                        tissue = "Colorectal"
                        sampleType = "Biopsy"
                        stain = "H&E"
                        analysisDate = "31 Aug 2026"
                        notes = "Demo data loaded for testing purposes."
                    },
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Text("Fill Demo Data")
                }
            }

            item {
                OutlinedTextField(
                    value = caseId,
                    onValueChange = { caseId = it },
                    label = { Text("Case ID") },
                    isError = isCaseIdDuplicate || caseId.isBlank(),
                    supportingText = {
                        if (isCaseIdDuplicate) {
                            Text("Case ID already exists. Please use a unique Case ID.", color = RedError)
                        } else {
                            Text("Auto-generated (editable)")
                        }
                    },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            item {
                OutlinedTextField(
                    value = patientId,
                    onValueChange = { patientId = it },
                    label = { Text("Patient ID") },
                    placeholder = { Text("PT-2026-XXXX") },
                    supportingText = { Text("Format: PT-YYYY-XXXX (Optional)") },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            item {
                OutlinedTextField(
                    value = patientName,
                    onValueChange = { patientName = it },
                    label = { Text("Patient Name") },
                    placeholder = { Text("e.g. John Doe") },
                    modifier = Modifier.fillMaxWidth(),
                    isError = patientName.isBlank()
                )
            }

            item {
                OutlinedTextField(
                    value = tissue,
                    onValueChange = { tissue = it },
                    label = { Text("Tissue / Organ") },
                    placeholder = { Text("e.g. Colorectal") },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            item {
                OutlinedTextField(
                    value = sampleType,
                    onValueChange = { sampleType = it },
                    label = { Text("Sample Type") },
                    placeholder = { Text("e.g. Biopsy") },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            item {
                OutlinedTextField(
                    value = stain,
                    onValueChange = { stain = it },
                    label = { Text("Stain") },
                    placeholder = { Text("e.g. H&E") },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            item {
                OutlinedTextField(
                    value = analysisDate,
                    onValueChange = { analysisDate = it },
                    label = { Text("Analysis Date") },
                    placeholder = { Text("e.g. 31 Aug 2026") },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            item {
                OutlinedTextField(
                    value = notes,
                    onValueChange = { notes = it },
                    label = { Text("Notes (Optional)") },
                    placeholder = { Text("Clinical observations, preliminary findings...") },
                    modifier = Modifier.fillMaxWidth(),
                    minLines = 3
                )
            }

            item {
                Button(
                    onClick = {
                        val cleanCaseId = caseId.trim().ifBlank { autoGeneratedCaseId }
                        val finalCaseId = if (com.example.colonpath_ai.data.SampleDataRepository.isCaseIdExists(cleanCaseId)) {
                            com.example.colonpath_ai.data.SampleDataRepository.generateNextCaseId()
                        } else {
                            cleanCaseId
                        }
                        val effectivePatientId = patientId.trim().ifBlank { com.example.colonpath_ai.data.SampleDataRepository.generateNextPatientId() }
                        val effectivePatientName = patientName.trim().ifBlank { "Anonymous Patient" }
                        val newCase = Case(
                            caseId = finalCaseId,
                            patient = PatientInfo(
                                patientId = effectivePatientId,
                                patientName = effectivePatientName,
                                notes = notes
                            ),
                            tissue = tissue.trim().ifBlank { "Colorectal" },
                            sampleType = sampleType.trim().ifBlank { "Biopsy" },
                            stain = stain.trim().ifBlank { "H&E" },
                            analysisDate = analysisDate.trim().ifBlank { "31 Aug 2026" },
                            status = CaseStatus.PENDING,
                            notes = notes
                        )
                        onProceed(newCase)
                    },
                    modifier = Modifier.fillMaxWidth().padding(vertical = 16.dp),
                    enabled = isFormValid
                ) {
                    Text("Proceed to Image Selection")
                }
            }

            item {
                Spacer(modifier = Modifier.height(100.dp))
            }
        }
    }
}
